secret:
    databaseUrl: ENC[AES256_GCM,data:afGDGw6aU3fl4ymGcFgM9zGMKv8y47H5QS2VeVHoPpSEy2yaHNii1cw3gVnKDY5TcFVD97IZkwGZL6NNglvgJYGvL/RdmPiu1j5AJ67B8WRRO6QBKluYgWTW,iv:JuK+gREyhcliE6Ey2MFVQ4PCR+HWWhuCx4MWm79d+dM=,tag:DWgZbrdXOkI+uv+nckd16A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Um5JWGtFVDdFSXZVbTRq
            UGtNYUJobEtnOUt3Y0JuWGc4S2pPa0xDQmk0CitpYlhqTnk1TFRCemlLY2RQRkVl
            RzY5bXppT1gxdkMwRnZsRzE2cFVyTE0KLS0tIG1UU0xYd3dOdmtUZUFIUG8rMDRF
            UGRzWnFLQzdwUWx6K2Exd01LejU0em8KKkekNPqJsK0fIGvyDRdrHqXyM2al23Au
            qhQoWJ71iadRpHJAo5J3pBJekfhftWyxu1LmMYg3tcxt16UceRvYCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ur9dh6j2jssv02xwfdh0ge7al7w5c4xmnyn46f5k8dj5snse2dzsm7nzyy
    lastmodified: "2026-08-04T12:42:53Z"
    mac: ENC[AES256_GCM,data:0pVrWcFpSuLALvJyLppPg5jc2cMhLiETWCtZ+HdVGdV2sHYpIv6XGEg41V4VeupAqZ7jqlUnBA8UlxvKn1jKBNsGza08v2MnVj7FrYuVZzTB0Ja0eLswX2e3FbRshWJLGOrxF09LSCjXPrinBiEQ4l0dOUhEeRSlLMDGUN20QBw=,iv:s2CRBV7sO2Ok8Ad7o8efwliYT0TWQjbIEHaXkvSwx2Q=,tag:3AExAYO4ZmGB++UekUOGjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
