apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: lihachev/backend:sha-02bae02bd6e45c07558a0f1baeb3e99889a902e6
          ports:
            - containerPort: 4545
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

            