secret:
    dbName: ENC[AES256_GCM,data:Zpnqllhof1Y=,iv:EQclGpnEobmZSVWLpVy8LtMTlg2TfhhnjuiKHAGYHOU=,tag:+7i5tfuptHy3JA5QNp7DsQ==,type:str]
    dbUser: ENC[AES256_GCM,data:Nqpj9NdZEr8=,iv:H9pZqIiFq+gY11Fo97k/7uyrsVZNvYWJFjcOesDUuEA=,tag:w0ohu2BDvOs+/BvhiVYDEw==,type:str]
    dbPassword: ENC[AES256_GCM,data:IfRu/szH0Ck=,iv:gQluNHIogk5j+IwNxe84AkSQE1GsdiIHtSD67tEb/9U=,tag:zD7M5qPMTO9z255zYd6e8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTnRKQXVNbG9qU1BiTXVL
            UDU3V1RISll5SHRCcHZUYys3c0ZJSjdZSkNBCmMwZ1dSNlZtODB2L21nU1NlU0dt
            bG5STjJJeTdwUXpWVjY4Qm9GSnBETUEKLS0tIGhIanVVVkY3N1ZvSUFMT1pRN1RX
            dm9TODNmYXpKUWs4bzFEWks3WDlrb0EKYqb5YoDijUeTa4J9x08QaGQNwu7RTv57
            sy6DPeQgosKrPrpxE5Sw8iq/E++KdMK2AZOM0GdQVX1lX9xdkAoKtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ur9dh6j2jssv02xwfdh0ge7al7w5c4xmnyn46f5k8dj5snse2dzsm7nzyy
    lastmodified: "2026-08-04T12:42:31Z"
    mac: ENC[AES256_GCM,data:MBUeI8Ug0hKH5sm+7zgxzJG3g+c7XLIzwStW14LNOKqrw8+yNsN5vjWFYrhb+is6y0stinvN3vTRsQI+O6YUyZ416/L6KJZnkIdqmDVQAUyWqUE6P1ci1ar1SP5F86esT23+o/+0WBswYmX+5M5uv9ZPStbJh+v4eEHb71jcvts=,iv:2mYyrDlAIHz9J+ZnhcDYcxtWaEk+H5bc4XoEEiACT60=,tag:aC3B//h0EXxcLqhYV8jGIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
