name: PR Check

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [23,24]
        include:
            node-version: 24
            experimental: true
        exclude:
          - os: windows-latest
            node-version: 23
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental==true }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Установка зависимостей
        run: npm ci

      - name: Линтинг
        run: npm run lint

      - name: Запуск тестов
        run: npm run test
